version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: Run rspec tests
          command: |
            bundle exec rspec
